# Site Build 
baseurl: /mobleylab.org

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Mobley Lab"
description:	       "A research group website"
author:              "the Mobley lab members"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
feed:
path: rss-feed.xml
