name: GH Actions CI
on: 
  push:
    branches:
      - gh-pages     
  pull_request:
    branches:
      - gh-pages

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        # using version 2 of https://github.com/actions/checkout
        uses: actions/checkout@v2

      - name: Setup ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true # caches installed gems
      
      - name: Install dependencies
        run: bundle install

      - name: Test build
        run: bundle exec jekyll build
